# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sks', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Teori'), (2, 'Praktik')], default=1)),
            ],
        ),
    ]
