# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
