# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0001_initial'),
        ('lecturers', '0002_lecture_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together=set([('name', 'study_programs')]),
        ),
    ]
