# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('courses', '__first__'),
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')])),
                ('classrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classrooms.Classroom')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.Course')),
                ('lectures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lecturers.Lecture')),
            ],
        ),
    ]
